[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'postgresql']

[phases.install]
cmds = ['python -m pip install --upgrade pip', 'python -m pip install -r requirements.txt']

[start]
cmd = 'bash start.sh'
