[phases.setup]
nixPkgs = ['python311', 'postgresql']

[phases.install]
cmds = ['cd bskt_app/server && pip install -r requirements.txt']

[phases.build]
cmds = ['echo "Build phase complete"']

[start]
cmd = 'bash start.sh'
