[build]
builder = "NIXPACKS"
buildCommand = "cd bskt_app/server && pip install -r requirements.txt"
watchPaths = ["bskt_app/server/**"]

[deploy]
startCommand = "bash start.sh"
healthcheckPath = "/test-cors"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
