"""Add historical_data_cache to sessions

Revision ID: ee4137552f19
Revises: 6f3131aa3ec2
Create Date: 2025-07-29 14:29:03.130173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee4137552f19'
down_revision: Union[str, Sequence[str], None] = '6f3131aa3ec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('historical_data_cache', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'historical_data_cache')
    # ### end Alembic commands ###
